### ISSUE TITLE
Hitting Github API rate limit causes TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by bawigga** [caskroom/caskroom.github.io#31]
When using the search feature on the website, I get the following exception in the console from [cask.js:112](https://github.com/caskroom/caskroom.github.io/blob/8cb4866bb44b2f22a99f22edbc2a7ca93e12ca32/js/cask.js#L112).

```
Uncaught TypeError: Cannot read property 'filter' of undefined
```

Looks like I'm also hitting the rate limit for the Github api which prevents the formulas from being brought in which results in caskList being undefined.

**Comment by radeksimko** [comment]
I do not experience described issue, but the page does seem to do 3 calls to the Github API without any credentials, which means that as an unauthenticated user, you can reload the whole page approximately 20 times per minute without hitting the limit, but the search doesn't count in these requests, as it's only searching in an already downloaded list.

> For unauthenticated requests, the rate limit allows you to make up to 60 requests per hour. Unauthenticated requests are associated with your IP address, and not the user making requests. 

https://developer.github.com/v3/#rate-limiting

Implementing authentication to get higher rate limit would be imho a bit overkill, unless we know that people are hitting these limits and there are some good reasons behind it.

What I think can be done is detecting these cases and displaying a meaningful & helpful error message.

**Comment by ndr-qef** [comment]
Our queries are rate-limited at 60 per hour, which is reasonable for a splash page. However, there are cases (e.g. shared IPs) where this limit can be reached rather easily.

I agree with @radeksimko that authenticating would be excessive, but an error message is certainly warranted.
