### ISSUE TITLE
Confusing text at homepage

### ISSUE THREAD

**Issue by rafaelbiriba** [caskroom/caskroom.github.io#38]
When you enter in caskroom website, you see:

"Install with ease" with a chrome installation example. But this is confusing because, you don't have cask yet.

I suggest move the "get cask" box to the top, before the examples.

**Comment by vitorgalvao** [comment]
Please do not open issues if you’re going to submit a PR right after.

**Comment by rafaelbiriba** [comment]
Sorry about that. It was not my intend to send the pull request. But I found some free time and decide to do it myself :)
