### ISSUE TITLE
Search results should give me something more than the name of each app

### ISSUE THREAD

**Issue by callumlocke** [caskroom/caskroom.github.io#40]
Some apps look interesting by their names but I have no idea what they are. Googling doesn't always help.

For example, what is the chrome-devtools cask? Aren't devtools built into Chrome? Is this some kind of external alternative that I might find useful? Currently there's no way to tell except by installing it.

Please add some more info, even if it's just a link to some kind of technical manifest about the cask?

**Comment by vitorgalvao** [comment]
No.

The suggestion is welcome, but [we don’t intend to become a discoverability service](https://github.com/caskroom/homebrew-cask/issues/4323#issuecomment-67257513). This has been [discussed and refused multiple times](https://github.com/caskroom/homebrew-cask/issues/5425#issuecomment-49512837), as [it is not part of the goals of homebrew-cask](https://github.com/caskroom/homebrew-cask/issues/3817#issuecomment-39868330). Amongst other things, the logistics are unsustainable.

**Comment by callumlocke** [comment]
Logistics?

All you need to do is add a "View cask" link to the cask `.rb` file on Github.

For example **chrome-devtools** could link to
https://github.com/caskroom/homebrew-cask/blob/master/Casks/chrome-devtools.rb

No logistics at all. The URL is based on the cask name, so it could be a one-line addition to your template.

**Comment by vitorgalvao** [comment]
Ah, I see, I thought you meant something like a description, or the like.

> Currently there's no way to tell except by installing it.

How so? `brew cask home {{name of cask}}`. Done.

**Comment by danielbayley** [comment]
It would be handy to simply display the `homepage` link alongside the `brew cask install #{app}` command…
