### ISSUE TITLE
Feature Request: Live Statistics Caskroom - Top Download List

### ISSUE THREAD

**Issue by strages** [caskroom/caskroom.github.io#42]
Hi Everybody,

Love the work that is in progress and already done on Brewcask. However I think the site is a little underwhelming. There is a search function on the website, which is pretty neat. However it doesn't show anything prior to input. 

It would be great for people to explore frequently used casks, as those apps probably can add a lot of value to their workflow when people don't know about them yet.

**Comment by alebcay** [comment]
[Homebrew Cask is not an app discovery platform.](https://github.com/caskroom/homebrew-cask/issues/198)
