### ISSUE TITLE
Feature Request: Download List Discovery

### ISSUE THREAD

**Issue by strages** [caskroom/caskroom.github.io#43]
Hi Everybody,

Love the work that is in progress and already done on brewcask. However I think the site is a little underwhelming. There is a search function on the website, which is pretty neat. However it only shows the command to install if you find the specific app. It would be great to discover apps that can be installed through brewcask. Doing this by showing a summary of what the app does, its website, its logo, active installs, etc. Maybe catagorise the search function. Reviews is a little too much, but a rating is not bad. etc (I would not put screenshots on it though)

what do you think?

**Comment by alebcay** [comment]
[Homebrew Cask is not an app discovery platform.](https://github.com/caskroom/homebrew-cask/issues/198)
