### ISSUE TITLE
Change "Get Cask" portion of Index.html

### ISSUE THREAD

**Issue by sbdchd** [caskroom/caskroom.github.io#45]
I think the last part of the index page, Get Cask, could be changed since it is no longer necessary to tap `caskroom/cask` for homebrew-cask to function.

**Comment by vitorgalvao** [comment]
I thought so as well, but then we removed it and that caused a lot of confusion. There’re some issues about it that I’m currently not finding.

**Comment by bazooka241** [comment]
The other day did not Thank really sorry.
That nothing had taken an arrogant attitude in spite of the absence of knowledge
It makes no and twice
Take a last chance. Please been studying from the 1.
