### ISSUE TITLE
Support HTTPS for caskroom.io

### ISSUE THREAD

**Issue by stevenatwork** [caskroom/caskroom.github.io#46]
See https://github.com/Homebrew/homebrew.github.io/issues/98 for brew.sh

https://support.cloudflare.com/hc/en-us/articles/203663694-How-do-I-enable-free-Universal-SSL-with-Github-

Cloudflare will do HTTPS for free with a simple dns change and no need to move away from Github pages.

**Comment by adidalal** [comment]
There's nothing sensitive (or even installable) on caskroom.io - am I missing something?

**Comment by alebcay** [comment]
Honestly, the only thing I can think of that anyone would ever bother to change in a MITM attack on using HTTP instead of HTTPS is the installation command, in which the command is changed into a malicious one instead.

Even then (the situation is already a bit of a stretch), I would think that (1) most new users would catch it, and (2) such a discrepancy would quickly be reported.

**Comment by vitorgalvao** [comment]
Why do most posts start with multiple paragraphs explaining the life story of the services used and why the writer decided to start using them and the hurdles they had to jump through to get it working the first time? I’m reading, aren’t I? I’m already interested and you’re sucking that interest out. Context is important, sure, but at least make it clear how to skip it. Rant finished.

> To get started, head over to CloudFlare and create an account.

Oh boy, one more account to keep track of, I’ll get right on that.

@stevenatwork To be clear, the rant has nothing to do with you or your suggestion. Your suggestion is good and I agree we should strive to have SSL in all websites. My issue is with the post with the instructions.

I have a few better suggestions (that will give the same results).

1. We forget the http://caskroom.io/ address (who’s paying for it, by the way, is that you, @phinze?) and just use https://caskroom.github.io/. Same effect, we don’t pay for the domain, and get https for free without needing extra setup and new accounts.
2. We make http://caskroom.io/ redirect to https://caskroom.github.io (it now works the other way around). The website is single page, so it’s not like it’ll make a different to users.

Option 2 seems best (less disruptive), but I’ll leave the decision to whoever is actually paying the domain.

**Comment by stevenatwork** [comment]
@adidalal The installer command is. See: https://thejh.net/misc/website-terminal-copy-paste

There's ISPs adding in ads etc as well but HTTPS should be enabled in this day and age.

@vitorgalvao I agree, the linked issue has a very quick instruction set that I wrote. https://github.com/Homebrew/homebrew.github.io/issues/98


I don't expect it to be done immediately but striving towards it would be great. :beer:

**Comment by adidalal** [comment]
That command isn't even needed anymore. Homebrew takes care of it

**Comment by phinze** [comment]
@vitorgalvao Hello! I do indeed have the domain name under my Namecheap acct. Happy to implement option 2 (the redirect) if that's consensus. Seems like a reasonable way forward to me.

**Comment by vitorgalvao** [comment]
@caskroom/maintainers Any objections? For context, we’re talking about implementing [option 2](https://github.com/caskroom/caskroom.github.io/issues/46#issuecomment-184689345).

**Comment by fanquake** [comment]
Agree with option 2.

**Comment by vitorgalvao** [comment]
@phinze Looks like we can go ahead with option 2.

**Comment by phinze** [comment]
Done and done! Give global DNS a bit to settle, but working well from here now.

**Comment by vitorgalvao** [comment]
Thank you. Working here now as well. Closing the issue, then.
