### ISSUE TITLE
Feature Request: Search and display description

### ISSUE THREAD

**Issue by lukekhamilton** [caskroom/caskroom.github.io#62]
Hey guys, be great if you could also search and display the description text of a cask on the site.

**Comment by commitay** [comment]
Do you mean the `name` field? We don't have descriptions.

**Comment by lukekhamilton** [comment]
Yeah that would be better than whats already there. The web search doesnt really give a lot of details.

**Comment by vitorgalvao** [comment]
You’re supposed to use the CLI tool to search, not the website. I wouldn’t refuse a well-made PR for the feature, but I also don’t see the point in the team spending time on it.
