### ISSUE TITLE
caskroom.io is down (expired?)

### ISSUE THREAD

**Issue by ealeksandrov** [caskroom/caskroom.github.io#64]
http://caskroom.io/ opens to parking page:

<img width="850" alt="screen shot 2018-02-21 at 15 26 00" src="https://user-images.githubusercontent.com/3132438/36479957-972713f8-171b-11e8-955d-ffa6b6b6815c.png">

**Comment by vitorgalvao** [comment]
Pinging @phinze in case that wasn’t on purpose.

But that domain has been abandoned for a while. It continued to work but only redirected to https://caskroom.github.io. You’ll notice there’s no mention of http://caskroom.io in the documentation.

Relevant discussion: https://github.com/caskroom/caskroom.github.io/issues/46

**Comment by ealeksandrov** [comment]
I agree with discussion and will change link in my project README to point to https://caskroom.github.io.
Thanks!

**Comment by phinze** [comment]
I can confirm that letting go of that domain was on purpose - I'm guessing it should become available soon if anybody wants to pick it up in the future! 👍
