### ISSUE TITLE
404 on search button at the bottom of the homepage

### ISSUE THREAD

**Issue by genr8r** [caskroom/caskroom.github.io#65]
I have a recurring issue that I first incorrectly reported in the wrong repo, but it looks like it is back...

https://github.com/caskroom/homebrew-cask/issues/46831

**Comment by reitermarkus** [comment]
On the old issue you said https://caskroom.io/search/, which doesn't exist anymore. https://caskroom.github.io/search/ is working fine.

**Comment by reitermarkus** [comment]
Wait a minute …

`https://caskroom.github.io/search/` -> 404
`https://caskroom.github.io/search` -> working

**Comment by reitermarkus** [comment]
Remove the version with the trailing slash from your history and you should be fine.

**Comment by genr8r** [comment]
I cleared my local browser cache to be sure. The button at the very bottom right of the caskroom.io homepage is linked to... http://caskroom.io/search/

That URL is 404. I think the button just needs an update to the github address.

**Comment by genr8r** [comment]
Actually checking further... if I hit the homepage at https://caskroom.github.io/ the relative url on the search button works great. However, I think visitors are just as (more?) likely to visit at http://caskroom.io/ which breaks the relative url behind the search button. So, you can either put the correct absolute url behind the search button or setup a 301 redirect to push all traffic from http://caskroom.io/ to https://caskroom.github.io/

**Comment by reitermarkus** [comment]
http://caskroom.io/ is not active anymore, and the link on the bottom of  https://caskroom.github.io/ clearly links to `/search`, not `/search/.

**Comment by reitermarkus** [comment]
> When I visit http://caskroom.io/ I get a webpage (with the broken button link) and search engines are still pointing to it.

I don't get a webpage, it just loads indefinitely. @phinze, shouldn't the domain already be expired?

**Comment by genr8r** [comment]
Technically it expires next year, but someone just registered (re-registered?) it a month ago...

https://who.is/whois/caskroom.io

Sorry for being so pesky. I just love what you all are doing and thought I would help a little. I didn't expect a 404 to turn into a thing.

**Comment by vitorgalvao** [comment]
> I didn't expect a 404 to turn into a thing.

Now I’m more concerned about who reregistered that domain and why.

**Comment by phinze** [comment]
Hi folks - Yeah this isn’t me. Best guess would be some automation that
parks on recently expired domains? Sorry I can’t be of more help here!

On Fri, May 11, 2018, at 3:56 PM, Vítor Galvão wrote:
>> I didn't expect a 404 to turn into a thing.


> Now I’m more concerned about who reregistered that domain and why.


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/caskroom/caskroom.github.io/issues/65#issuecomment-388483367

**Comment by genr8r** [comment]
No worries. If you cared it looks like it is still pulling the github code for the official page. IF that is correct, you could use an absolute urls on the homepage for all the assets and rogue page at caskroom.io should pull them in. That is a bit of speculation and if the domain is just parked this should only be a short term issue anyway as we are likely to see ads and a resulting drop in SERP visibility anyway. Anyway, sorry for all the run around and thanks again for your work. It great stuff!
